### ISSUE TITLE
Problem with ArrayTypeDetailsImpl#getName

### ISSUE THREAD

**Issue by cigaly** [hibernate/hibernate-models#103]
Attached is test case that is failing
[MultiDimensionalIntegerArrayTypeTest.txt](https://github.com/user-attachments/files/17269545/MultiDimensionalIntegerArrayTypeTest.txt)

I've noticed it while testing something on Hibernate ORM, but the problem seems to be in `org.hibernate.models.internal.ArrayTypeDetailsImpl#getName`. When run, test is failing with message
```
org.opentest4j.AssertionFailedError: Returned class ==> expected: <int[][][][]> but was: <int[][][][][][][][][][]>
```

Source of the problem is inside the loop:

```
		while ( type.getTypeKind() == Kind.ARRAY ) {
			int dimensions = type.asArrayType().getDimensions();
			while ( dimensions-- > 0 ) {
				builder.append( '[' );
			}
			type = type.asArrayType().getConstituentType();
		}
```

This way, number of dimensions in returned class will be `d*(d+1)/2` instead of just `d` since every constituent type has dimension one less that its 'parent'

Correct code should be imply:

```
		while ( type.getTypeKind() == Kind.ARRAY ) {
			builder.append( '[' );
			type = type.asArrayType().getConstituentType();
		}
```

**Comment by sebersole** [comment]
Thanks @cigaly !

Do you agree to let me use that test in this project (different licenses)?

**Comment by cigaly** [comment]
Yes, of course

**Comment by sebersole** [comment]
Thanks!  Sorry to ask, but its important to have explicit approval :)

**Comment by sebersole** [comment]
Fixed
