### ISSUE TITLE
Work on generics / parameterized-types

### ISSUE THREAD

**Issue by sebersole** [hibernate/hibernate-models#21]
Fully support for generics / parameterized-types

**Comment by beikov** [comment]
I think it would be best to make `ClassDetails` extends `TypeDetails` and let members expose `TypeDetails` instead of `ClassDetails`. Then you can mirror the respective `ParameterizedType` etc. in that hierarchy.

**Comment by sebersole** [comment]
> I think it would be best to make `ClassDetails` extends `TypeDetails` and let members expose `TypeDetails` instead of `ClassDetails`. Then you can mirror the respective `ParameterizedType` etc. in that hierarchy.

Yep, that was my initial thought as well.  Its one situation which Jandex and the JDK model differently.  I went with the Jandex approach for the time being, which is to have completely separate hierarchies.  So `ClassDetails` does not extend `TypeDetails` - instead there is a `ClassTypeDetails` which wraps a `ClassDetails`
