### ISSUE TITLE
Remove createUsage methods that take a lambda callback

### ISSUE THREAD

**Issue by beikov** [hibernate/hibernate-models#68]
There is `AnnotationDescriptor#ceateUsage` and maybe utility methods that take a lambda callback for initializing the `MutableAnnotationUsage`. Since that essentially produces anonymous hidden classes at runtime, this should IMO be removed. The value of those methods is questionable anyway.

**Comment by mbladel** [comment]
WDYT about removing the lambda configuration from `DynamicClassDetails#applyAttribute` as well? After all that method returns the `DynamicFieldDetails` it created so one can simply apply the configuration on the returned value.
